### ISSUE TITLE
School

### ISSUE THREAD

**Issue by bolric17** [BlackCapCoder/CampusLocator#1]
@BlackCapCoder Wanna come to school today?

**Comment by BlackCapCoder** [comment]
That was a bit too early for me; sorry

**Comment by BlackCapCoder** [comment]
I am happy to come to school right now I guess?

**Comment by BlackCapCoder** [comment]
@bolric17 Do you wanna come to school today?

**Comment by bolric17** [comment]
That was my plan, but I felt bad this morning, so I didnt make it.
